@startuml
start

:Подготовка моделей;
partition "Обучение на подвыборках LaRS" {
    :Загрузить открытый набор данных LaRS;
    :Сформировать 3 подвыборки с частичным пересечением;
    fork
        :Обучить SegFormer на подвыборке 1;
    fork again
        :Обучить Mask2Former на подвыборке 2;
    fork again
        :Обучить BEiT на подвыборке 3;
    end fork
}

:Загрузить сырые данные (видеосъёмка);

partition "Автоматическая аннотация" {
    :Три модели выполняют предсказания
    на одних и тех же сырых данных;
    :Взять первое изображение из набора предсказаний;

    while (Есть ещё изображения?) is (да)
        :Оценить согласованность трёх масок
        для текущего изображения;

        if (Согласованность хорошая?) then (да)
            :Добавить картинку в Стадию1;
            note left: Стадия1 = картинки + маски
        else (нет)
            :Отправить картинку и среднюю маску
            на ручную доразметку;
            :Получить ручную разметку;
            :Добавить картинку в Стадию1;
        endif

        :Перейти к следующему изображению;
    endwhile (нет)
}

:Инициализировать Финальный датасет как пустой набор;

partition "Итеративное улучшение" {
    while (Стадия1 не пуста?) is (да)
        :Дообучить лучшую модель на разметке из Стадии1;
        :Получить предсказания дообученной модели
        на изображениях из Стадии1;
        note right: Эти предсказания формируют Стадию2
        :Использовать исходную разметку Стадии1
        как эталонную (ground truth);
        :Сравнить предсказания из Стадии2
        с эталонной разметкой Стадии1;
        :Вычислить метрику ошибочности
        для каждого элемента Стадии1;
        :Разделить элементы Стадии1 по качеству разметки;

        if (Качество хорошее?) then (да)
            :Добавить элемент в Финальный датасет;
            :Удалить элемент из Стадии1;
        else (нет)
            :Отправить на ручную доразметку;
            :Получить исправленную разметку;
            :Вернуть элемент в Стадию1
            с новой разметкой;
        endif
    endwhile (нет)
}

:Финальный датасет собран;

stop
@enduml